function getRandomImage() {
//declare an array to store the images
var randomImage = new Array();

//insert the URL of images in array
randomImage[0] = "images/soda1.jpg";
randomImage[1] = "images/soda2.jpg";
randomImage[2] = "images/soda3.jpg";
randomImage[3] = "images/soda4.jpg";
randomImage[4] = "images/soda5.jpg";
randomImage[5] = "images/soda6.jpg";


//generate a number and provide to the image to generate randomly
var number = Math.floor(Math.random()*randomImage.length);

//return the images generated by a random number
return document.getElementById("result").innerHTML = '<img src="'+randomImage[number]+'" />';
}
